name: GraphQL Environment Indicator
type: module
description: GraphQL support for environment_indicator.
package: GraphQL
core_version_requirement: ^9.3 || ^10 || ^11
dependencies:
  - graphql_core_schema:graphql_core_schema
  - environment_indicator:environment_indicator

# Information added by Drupal.org packaging script on 2025-01-10
version: '1.0.22'
project: 'graphql_core_schema'
datestamp: 1736503776
